### ISSUE TITLE
Tenant issue encountered when starting

### ISSUE THREAD

**Issue by Solodye** [sentilo/sentilo#77]
Here is the problem I encountered
```
2024-09-29 13:48:06,661 SGT [http-nio-8080-exec-4] INFO  org.sentilo.web.catalog.interceptor.RequestLoggingInterceptor - Incoming request [remote_addr=0:0:0:0:0:0:0:1;request=GET /sentilo-catalog-web/status/]
2024-09-29 13:48:06,664 SGT [http-nio-8080-exec-4] ERROR org.sentilo.web.catalog.aop.aspect.CatalogExceptionTranslationInterceptor - SIE05-1727588886664 - Internal system error.java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl.getDefaultTenant(UserConfigServiceImpl.java:138)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl.getRequestTenant(UserConfigServiceImpl.java:132)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl.refreshCatalogUserConfigContext(UserConfigServiceImpl.java:83)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl$$FastClassBySpringCGLIB$$41c3b5e6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl$$EnhancerBySpringCGLIB$$4367d62b.refreshCatalogUserConfigContext(<generated>)
	at org.sentilo.web.catalog.interceptor.UserConfigInterceptor.preHandle(UserConfigInterceptor.java:45)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1065)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)

2024-09-29 13:48:06,664 SGT [http-nio-8080-exec-4] WARN  org.sentilo.web.catalog.logging.exceptions - Resolved [org.sentilo.web.catalog.exception.CatalogException: ; nested exception is java.lang.IndexOutOfBoundsException: Index: 0, Size: 0]
2024-09-29 13:48:06,694 SGT [http-nio-8080-exec-5] ERROR org.sentilo.web.catalog.aop.aspect.CatalogExceptionTranslationInterceptor - SIE05-1727588886693 - Internal system error.java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1311)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl.getDefaultTenant(UserConfigServiceImpl.java:138)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl.getRequestTenant(UserConfigServiceImpl.java:132)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl.refreshCatalogUserConfigContext(UserConfigServiceImpl.java:83)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl$$FastClassBySpringCGLIB$$41c3b5e6.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
	at org.sentilo.web.catalog.service.impl.UserConfigServiceImpl$$EnhancerBySpringCGLIB$$4367d62b.refreshCatalogUserConfigContext(<generated>)
	at org.sentilo.web.catalog.interceptor.UserConfigInterceptor.preHandle(UserConfigInterceptor.java:45)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1065)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
```

Here is the configuration:
Latest mongo db docker: https://hub.docker.com/_/mongo
Latest redis: https://hub.docker.com/_/redis
Tomcat 9.0.95

I executed the init_data.js.

**Comment by sentilo-io** [comment]
Hi @Solodye,

I seems that you didn't initialize the mongodb basic data. Please, check this out: https://sentilo.readthedocs.io/en/latest/setup.html#data-load 

Also keep in mind that Sentilo hasn't been tested with the last versions of MongoDB or Redis. The versions used for this Sentilo version were: 
- Redis 6.2.2
- MongoDB 4.4.2

Hope it helps,
Support team
